### PR TITLE
(#7) Add and Upddate ClickOnce docs

### LINKED ISSUE #7: Add documentation for Boxstarter.WebLaunch
I like to ask why the oneclick installer documentation is removed from the website
after a small discussion on gitter Paul @pauby he found the commit that has removed the reference to http://www.boxstarter.org/package

https://github.com/chocolatey/boxstarter/commit/da818feddd573267b1e10c490628e653800d1637#diff-c6e190b284633c48e39e55049da3cce8

i hope the function is not deprecated, i use this on a daily basis

### PR DESCRIPTION
**Pull request by pauby**
## Description Of Changes
Add back in the ClickOnce installer docs that were removed.

## Motivation and Context
The ClickOnce installer docs were removed when it was removed from Boxstarter. Chocolatey brought this back again but never restored the docs for it.

## Testing
Docker container.

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [ ] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

Fixes #7 

## Change Checklist

* [X] Requires a change to the documentation
* [X] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [ ] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

### CODE REVIEW

**Comment by pauby** [comment]
The main file for this is called `weblauncher.cshtml`. There is also a `learn\weblauncher.cshtml` file too. As the one we are amending here hasn't been used on the site, and therefore indexed, for a long time I think we should take the opportunity to rename it to, say, `clickonceinstaller.cshtml`.

Thoughts?

**Review by flcdrg — APPROVED** [review]

**Comment by flcdrg** [comment]
Renaming sounds good

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@pauby thanks for getting this added back in!

**Pull request merged**
