### PR TITLE
(#10) Use full command for cinst and cpush

### LINKED ISSUE #10: Remove references to deprecated functions
## Is Your Feature Request Related To A Problem? Please describe.
The Boxstarter documentation uses a lot of Chocolatey command shortcuts. 

## Describe The Solution. Why is it needed?
As these are being [deprecated](https://github.com/chocolatey/choco/issues/2642), we should remove them now and use the full Chocolatey CLI commands.

## Additional Context.

N/A

## Related Issues

- https://github.com/chocolatey/choco/issues/2642

### PR DESCRIPTION
**Pull request by pauby**
## Description Of Changes
Removed the Chocolatey CLI commands scoped for deprecation in a future version.

## Motivation and Context
The Chocolatey CLI commands are scheduled for deprecation in v2.0 of Chocolatey.

## Testing
Docker container.

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [ ] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

Fixes #10 

## Change Checklist

* [x] Requires a change to the documentation
* [x] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [ ] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

### CODE REVIEW

**Review by flcdrg — APPROVED** [review]

**Comment by mwallner** [comment]
:information_source:  While I agree with these changes I want to keep in mind that the removal of those deprecated aliases will not break any functionality in boxstarter packages, even if the used chocolatey version does not feature them anymore.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@pauby thanks for getting this updated!

**Comment by gep13** [comment]
> @mwallner said...
While I agree with these changes I want to keep in mind that the removal of those deprecated aliases will not break any functionality in boxstarter packages, even if the used chocolatey version does not feature them anymore.

Agreed. However, from a consistency point of view, I think it makes sense to use the same thing in both Chocolatey and Boxstarter.

**Pull request merged**
